sudo: required
services:
  - docker

before_install:
  - docker build -t react-test -f client/Dockerfile.dev client

script:
  - docker run react-test npm test -- --coverage

after_success:
  - docker build -t omniasetty/multi-client ./client
  - docker build -t omniasetty/multi-nginx ./nginx
  - docker build -t omniasetty/multi-server ./server
  - docker build -t omniasetty/multi-worker ./worker

  #Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker push omniasetty/multi-client
  - docker push omniasetty/multi-nginx
  - docker push omniasetty/multi-server
  - docker push omniasetty/multi-worker

  deploy:
    provide: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-516893405204
    bucket_path: docker-multi
    on: 
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: $AWS_SECRET_KEY
